# Discharges - Changing keys to their corresponding catalog descriptions

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Load dataset

In [2]:
#Discharges datasets
file = '../../Data/Databases/Data Integration/egresos2010_2022.csv'
egresos = pd.read_csv(file, on_bad_lines='skip')
egresos.head()

C:\Users\lili_\AppData\Local\Temp\ipykernel_15692\1216086817.py:3: DtypeWarning: Columns (11,19) have mixed types. Specify dtype option on import or set low_memory=False.
  egresos = pd.read_csv(file, on_bad_lines='skip')

,ID,CLUES,EGRESO,INGRE,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,MOTEGRE,DIAG_INI,AFECPRIN,VEZ,INFEC,CAUSAEXT
0,1,ASSSA000025,04/01/2010,04/01/2010,1,2.0,2,2.0,2,999.0,...,1,1,1.0,1.0,2.0,C492,C492,2,2.0,NaN
1,2,ASSSA000025,30/12/2009,30/12/2009,1,3.0,5,NaN,2,999.0,...,1,1,1.0,1.0,2.0,C910,C910,2,2.0,NaN
2,3,ASSSA000025,06/01/2010,06/01/2010,1,3.0,6,NaN,1,999.0,...,2,3,1.0,1.0,2.0,C910,C910,2,2.0,NaN
3,4,ASSSA000025,05/01/2010,05/01/2010,1,3.0,5,NaN,1,999.0,...,10,3,1.0,1.0,2.0,C910,C910,2,2.0,NaN
4,5,ASSSA000025,04/01/2010,04/01/2010,1,3.0,18,NaN,1,999.0,...,1,1,1.0,1.0,2.0,N180,N180,2,2.0,NaN

In [4]:
#Affections keys
file = '../../Data/Keys/CLAVES_AFEC.xlsx'
claves = pd.read_excel(file)
claves.head()

,CONSECUTIVO,LETRA,CATALOG_KEY,NOMBRE,CODIGOX,LSEX,LINF,LSUP,TRIVIAL,ERRADICADO,...,PRIN_SINAC_SUBGRUPO,DESCRIPCION_SINAC_SUBGRUPO,DAGA,ASTERISCO,PRIN_MM,PRIN_MM_GRUPO,DESCRIPCION_MM_GRUPO,PRIN_MM_SUBGRUPO,DESCRIPCION_MM_SUBGRUPO,COD_ADI_MORT
0,1,A,A00,CÓLERA,NO,NO,NO,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,2,A,A000,"CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CH...",NO,NO,NO,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
2,3,A,A001,"CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL...",NO,NO,NO,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,4,A,A009,"CÓLERA, NO ESPECIFICADO",NO,NO,NO,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
4,5,A,A01,FIEBRES TIFOIDEA Y PARATIFOIDEA,NO,NO,NO,NO,NO,NO,...,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO

## Change date format

In [31]:
egresos['EGRESO'] = pd.to_datetime(egresos['EGRESO'], dayfirst=True)
egresos['INGRE'] = pd.to_datetime(egresos['INGRE'], dayfirst=True)

## Replace keys

In [7]:
#Hospital keys
egresos['CLUES']= egresos['CLUES'].replace(['ASSSA000025', 'ASSSA000030', 'ASSSA000404', 'ASSSA000614', 
                                            'ASSSA000655', 'ASSSA001331'],
                                           ['CENTENARIO HOSPITAL MIGUEL HIDALGO', 'HOSPITAL GENERAL TERCER MILENIO', 
                                            'HOSPITAL GENERAL CALVILLO', 'HOSPITAL GENERAL PABELLÓN DE ARTEAGA', 
                                            'HOSPITAL GENERAL RINCÓN DE ROMOS', 'CENTENARIO HOSPITAL MIGUEL HIDALGO'])

In [8]:
# Select the first 3 characters from the affections key (general affection)
egresos['DIAG_INI'] = egresos['DIAG_INI'].str[:3]
egresos['AFECPRIN'] = egresos['AFECPRIN'].str[:3]
egresos['CAUSAEXT'] = egresos['CAUSAEXT'].str[:3]

In [9]:
egresos.head()

,ID,CLUES,EGRESO,INGRE,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,MOTEGRE,DIAG_INI,AFECPRIN,VEZ,INFEC,CAUSAEXT
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,2.0,2,2.0,2,999.0,...,1,1,1.0,1.0,2.0,C49,C49,2,2.0,NaN
1,2,CENTENARIO HOSPITAL MIGUEL HIDALGO,30/12/2009,30/12/2009,1,3.0,5,NaN,2,999.0,...,1,1,1.0,1.0,2.0,C91,C91,2,2.0,NaN
2,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,06/01/2010,06/01/2010,1,3.0,6,NaN,1,999.0,...,2,3,1.0,1.0,2.0,C91,C91,2,2.0,NaN
3,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,05/01/2010,05/01/2010,1,3.0,5,NaN,1,999.0,...,10,3,1.0,1.0,2.0,C91,C91,2,2.0,NaN
4,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,3.0,18,NaN,1,999.0,...,1,1,1.0,1.0,2.0,N18,N18,2,2.0,NaN

In [10]:
# Retain only the required columns
claves = claves[['CATALOG_KEY','NOMBRE']]
claves.rename(columns={'CATALOG_KEY':'CLAVE'}, inplace = True)
claves.head()

  CLAVE                                             NOMBRE
0   A00                                             CÓLERA
1  A000  CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO CH...
2  A001  CÓLERA DEBIDO A VIBRIO CHOLERAE 01, BIOTIPO EL...
3  A009                            CÓLERA, NO ESPECIFICADO
4   A01                    FIEBRES TIFOIDEA Y PARATIFOIDEA

In [11]:
#Check duplicates
claves[claves['CLAVE'].duplicated()]

      CLAVE                                             NOMBRE
68      A09  DIARREA Y GASTROENTERITIS DE PRESUNTO ORIGEN I...
1352    C80           TUMOR MALIGNO DE SITIOS NO ESPECIFICADOS
3945    I48                     FIBRILACIÓN Y ALETEO AURICULAR
4938    K85                                 PANCREATITIS AGUDA
5323    L89                                 ÚLCERA DE DECÚBITO
5663    M45                          ESPONDILITIS ANQUILOSANTE
6797    O60                                    PARTO PREMATURO
7002    O96  MUERTE MATERNA DEBIDA A CUALQUIER CAUSA OBSTÉT...
7007    O97  MUERTE POR SECUELAS DE CAUSAS OBSTÉTRICAS DIRE...
8190    R17                          ICTERICIA NO ESPECIFICADA
8528    R95              SÍNDROME DE LA MUERTE SÚBITA INFANTIL
10062   U92                           REINCIDENCIA DE COVID-19

In [12]:
# Drop duplicates
claves.drop_duplicates(subset = ['CLAVE'], keep = 'last', inplace = True)

In [13]:
# Merge the key table with discharges table for initial diagnosis column
egresos.rename(columns={'DIAG_INI':'CLAVE'}, inplace = True)
egresos = egresos.merge(claves, how = 'left', on = 'CLAVE')
egresos.rename(columns={'NOMBRE':'DIAG_INI'}, inplace = True)
egresos.drop(['CLAVE'], axis = 1, inplace = True)
egresos.head()

,ID,CLUES,EGRESO,INGRE,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,MOTEGRE,AFECPRIN,VEZ,INFEC,CAUSAEXT,DIAG_INI
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,2.0,2,2.0,2,999.0,...,1,1,1.0,1.0,2.0,C49,2,2.0,NaN,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...
1,2,CENTENARIO HOSPITAL MIGUEL HIDALGO,30/12/2009,30/12/2009,1,3.0,5,NaN,2,999.0,...,1,1,1.0,1.0,2.0,C91,2,2.0,NaN,LEUCEMIA LINFOIDE
2,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,06/01/2010,06/01/2010,1,3.0,6,NaN,1,999.0,...,2,3,1.0,1.0,2.0,C91,2,2.0,NaN,LEUCEMIA LINFOIDE
3,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,05/01/2010,05/01/2010,1,3.0,5,NaN,1,999.0,...,10,3,1.0,1.0,2.0,C91,2,2.0,NaN,LEUCEMIA LINFOIDE
4,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,3.0,18,NaN,1,999.0,...,1,1,1.0,1.0,2.0,N18,2,2.0,NaN,ENFERMEDAD RENAL CRÓNICA

In [14]:
# Merge the key table with discharges table for principal affection column.
egresos.rename(columns={'AFECPRIN':'CLAVE'}, inplace = True)
egresos = egresos.merge(claves, how = 'left', on = 'CLAVE')
egresos.rename(columns={'NOMBRE':'AFECPRIN'}, inplace = True)
egresos.drop(['CLAVE'], axis = 1, inplace = True)
egresos.head()

,ID,CLUES,EGRESO,INGRE,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,MOTEGRE,VEZ,INFEC,CAUSAEXT,DIAG_INI,AFECPRIN
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,2.0,2,2.0,2,999.0,...,1,1,1.0,1.0,2.0,2,2.0,NaN,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...
1,2,CENTENARIO HOSPITAL MIGUEL HIDALGO,30/12/2009,30/12/2009,1,3.0,5,NaN,2,999.0,...,1,1,1.0,1.0,2.0,2,2.0,NaN,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE
2,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,06/01/2010,06/01/2010,1,3.0,6,NaN,1,999.0,...,2,3,1.0,1.0,2.0,2,2.0,NaN,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE
3,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,05/01/2010,05/01/2010,1,3.0,5,NaN,1,999.0,...,10,3,1.0,1.0,2.0,2,2.0,NaN,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE
4,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,3.0,18,NaN,1,999.0,...,1,1,1.0,1.0,2.0,2,2.0,NaN,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA

In [15]:
# Merge the key table with discharges table for external cause column.
egresos.rename(columns={'CAUSAEXT':'CLAVE'}, inplace = True)
egresos = egresos.merge(claves, how = 'left', on = 'CLAVE')
egresos.rename(columns={'NOMBRE':'CAUSAEXT'}, inplace = True)
egresos.drop(['CLAVE'], axis = 1, inplace = True)
egresos.head()

,ID,CLUES,EGRESO,INGRE,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,MOTEGRE,VEZ,INFEC,DIAG_INI,AFECPRIN,CAUSAEXT
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,2.0,2,2.0,2,999.0,...,1,1,1.0,1.0,2.0,2,2.0,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,NaN
1,2,CENTENARIO HOSPITAL MIGUEL HIDALGO,30/12/2009,30/12/2009,1,3.0,5,NaN,2,999.0,...,1,1,1.0,1.0,2.0,2,2.0,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,NaN
2,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,06/01/2010,06/01/2010,1,3.0,6,NaN,1,999.0,...,2,3,1.0,1.0,2.0,2,2.0,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,NaN
3,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,05/01/2010,05/01/2010,1,3.0,5,NaN,1,999.0,...,10,3,1.0,1.0,2.0,2,2.0,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,NaN
4,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,3.0,18,NaN,1,999.0,...,1,1,1.0,1.0,2.0,2,2.0,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,NaN

In [16]:
# Reorder columns
v_keep = ['ID', 'CLUES', 'INGRE', 'EGRESO', 'DIAS_ESTA', 'CVEEDAD','EDAD', 'NACIOEN', 'SEXO', 'PESO', 'TALLA', 'DERHAB',
         'MUNIC', 'LOC', 'TIPSERV', 'PROCED', 'DIAG_INI', 'AFECPRIN', 'VEZ', 'CAUSAEXT', 'INFEC', 'MOTEGRE']
egresos = egresos[v_keep]
egresos.head()

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,2.0,2,2.0,2,999.0,...,1,1,1.0,1.0,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,2,NaN,2.0,2.0
1,2,CENTENARIO HOSPITAL MIGUEL HIDALGO,30/12/2009,30/12/2009,1,3.0,5,NaN,2,999.0,...,1,1,1.0,1.0,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,2,NaN,2.0,2.0
2,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,06/01/2010,06/01/2010,1,3.0,6,NaN,1,999.0,...,2,3,1.0,1.0,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,2,NaN,2.0,2.0
3,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,05/01/2010,05/01/2010,1,3.0,5,NaN,1,999.0,...,10,3,1.0,1.0,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,2,NaN,2.0,2.0
4,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,3.0,18,NaN,1,999.0,...,1,1,1.0,1.0,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,2,NaN,2.0,2.0

In [17]:
#Change CVEEDAD keys to their description
egresos['CVEEDAD'].replace({0:'HORAS', 1: 'DIAS', 2:'MESES',3:'AÑOS', 9:'NE'}, inplace = True)

In [18]:
#Change NACIOEN keys to their description
egresos['NACIOEN'].replace({1:'SI',2:'NO', 8:'NA', 999:'NE'}, inplace = True)

In [19]:
# Change SEXO keys to their description
egresos['SEXO'].replace({1:'H', 2:'M', 9:'NE', 999:'NE'}, inplace = True)

In [20]:
# Replace letters to numbers
egresos['DERHAB'].replace({'G':12}, inplace = True)

In [21]:
# Change DERHAB data type
egresos['DERHAB'] = egresos['DERHAB'].astype(float)

In [22]:
# Change DERHAB keys to their description
egresos['DERHAB'].replace({0:'NINGUNA', 1: 'IMSS', 2:'ISSSTE', 3:'PEMEX', 4:'SEDENA', 5:'SEMAR',
                          6:'GOBIERNO ESTATAL', 7:'SEGURO PRIVADO', 8: 'SEGURO POPULAR', 9:'NE', 10:'OTRO',
                          11:'INSABI', 12:'GRATUIDAD'}, inplace = True)

In [23]:
#Change MUNIC keys to their description
egresos['MUNIC'].replace({1:'AGUASCALIENTES', 2:'ASIENTOS', 3:'CALVILLO', 4:'COSIO', 5:'JESUS MARIA',
                         6:'PABELLON DE ARTEAGA', 7:'RINCON DE ROMOS', 8:'SAN JOSE DE GRACIA',
                         9:'TEPEZALA', 10:'EL LLANO',11:'SAN FRANCISCO DE LOS ROMO', 999: 'NE'}, inplace = True)

In [24]:
#Change TIPSERV keys to their description
egresos['TIPSERV'].replace({1:'NORMAL', 2:'CORTA ESTANCIA', 202:np.nan}, inplace = True)

In [25]:
#Change PROCED keys to their description
egresos['PROCED'].replace({1:'CONSULTA EXTERNA', 2:'URGENCIAS', 3:'REFERIDO', 4:'OTRO',
                          6:'CUNERO PATOLOGICO', 9:'NE'}, inplace = True)

In [26]:
#Replce letters with numbers
egresos['VEZ'].replace({'V486':9}, inplace = True)
#CChange data type to float
egresos['VEZ'] = egresos['VEZ'].astype(float)
# Change VEZ keys to their description
egresos['VEZ'].replace({1:'PRIMERA', 2:'SUBSECUENTE', 9:'NE'}, inplace = True)

In [27]:
#Change INFEC keys to their description
egresos['INFEC'].replace({1:'SI', 2:'NO', 9:'NE'}, inplace = True)

In [28]:
#Change CVEEDAD keys to their description
egresos['MOTEGRE'].replace({1:'CURACION', 2:'MEJORIA', 3:'VOLUNTARIO', 4:'TRASLADO', 5:'DEFUNCION',
                           6:'FUGA', 7:'OTRO', 9:'NE'}, inplace = True)

In [29]:
egresos

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,MESES,2,NO,M,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NaN,NO,MEJORIA
1,2,CENTENARIO HOSPITAL MIGUEL HIDALGO,30/12/2009,30/12/2009,1,AÑOS,5,NaN,M,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
2,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,06/01/2010,06/01/2010,1,AÑOS,6,NaN,H,999.0,...,ASIENTOS,3,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
3,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,05/01/2010,05/01/2010,1,AÑOS,5,NaN,H,999.0,...,EL LLANO,3,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
4,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,04/01/2010,04/01/2010,1,AÑOS,18,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321257,321258,HOSPITAL GENERAL PABELLÓN DE ARTEAGA,2022-09-15,2022-09-15,1,AÑOS,19,NA,M,57.8,...,PABELLON DE ARTEAGA,1,NORMAL,URGENCIAS,PARTO ÚNICO ESPONTÁNEO,PARTO ÚNICO ESPONTÁNEO,PRIMERA,NaN,NO,MEJORIA
321258,321259,HOSPITAL GENERAL PABELLÓN DE ARTEAGA,2022-09-14,2022-09-15,1,AÑOS,23,NA,M,68.0,...,PABELLON DE ARTEAGA,1,NORMAL,URGENCIAS,TAQUICARDIA PAROXÍSTICA,TAQUICARDIA PAROXÍSTICA,PRIMERA,NaN,NO,MEJORIA
321259,321260,HOSPITAL GENERAL PABELLÓN DE ARTEAGA,2022-09-15,2022-09-16,1,AÑOS,22,NA,M,87.0,...,PABELLON DE ARTEAGA,1,NORMAL,URGENCIAS,ABORTO MÉDICO,ABORTO MÉDICO,PRIMERA,NaN,NO,MEJORIA
321260,321261,HOSPITAL GENERAL PABELLÓN DE ARTEAGA,2022-09-07,2022-09-16,9,AÑOS,24,NA,M,71.9,...,JESUS MARIA,1,NORMAL,URGENCIAS,ATENCIÓN MATERNA POR OTROS PROBLEMAS FETALES C...,ATENCIÓN MATERNA POR OTROS PROBLEMAS FETALES C...,PRIMERA,NaN,NO,VOLUNTARIO
321261,321262,HOSPITAL GENERAL PABELLÓN DE ARTEAGA,2022-09-16,2022-09-17,1,AÑOS,20,NA,M,94.0,...,PABELLON DE ARTEAGA,1,NORMAL,URGENCIAS,PARTO ÚNICO ESPONTÁNEO,PARTO ÚNICO ESPONTÁNEO,PRIMERA,NaN,NO,MEJORIA

## Drop records before 2010

In [32]:
egresos = egresos[egresos['EGRESO'].dt.year >= 2010]

## Export to csv

In [33]:
from pathlib import Path 
#Discharges
filepath = Path('../../Data/Databases/Keys/egresos.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
egresos.to_csv(filepath, index = False)