# More Data Cleaning

## Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load datasets

In [2]:
#Discharges
file = '../../Data/Databases/Keys/egresos.csv'
egresos = pd.read_csv(file, on_bad_lines='skip')
egresos.head()

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,MESES,2,NO,M,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NaN,NO,MEJORIA
1,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,6,NaN,H,999.0,...,ASIENTOS,3,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
2,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,5,NaN,H,999.0,...,EL LLANO,3,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
3,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,18,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
4,8,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,17,NaN,M,999.0,...,JESUS MARIA,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA

In [4]:
# Change date columns to date format
egresos['EGRESO'] = pd.to_datetime(egresos['EGRESO'])
egresos['INGRE'] = pd.to_datetime(egresos['INGRE'])

In [5]:
#Affections
file = '../../Data/Databases/Keys/afecciones.csv'
afecciones = pd.read_csv(file, on_bad_lines='skip')
afecciones.head()

      ID  NUMAFEC                                        AFEC
0    399        2  FRACTURA DE HUESOS DEL CRÁNEO Y DE LA CARA
1    399        3                      FRACTURA DEL ANTEBRAZO
2    399        1            HIPERTENSIÓN ESENCIAL (PRIMARIA)
3  25245        1             ATENCIÓN PARA LA ANTICONCEPCIÓN
4  25569        1             ATENCIÓN PARA LA ANTICONCEPCIÓN

In [7]:
#Procedures
file = '../../Data/Databases/Keys/procedimientos.csv'
procedimientos = pd.read_csv(file, on_bad_lines='skip')
procedimientos.head()

      ID  NUMPROMED        TIPO       PROMED     ANEST QUIROF    QH    QM
0  10952          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN  99.0  99.0
1  23436          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN   1.0   0.0
2  23659          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN   1.0   0.0
3  23789          1  QUIRURGICO  LAPAROTOMÍA   GENERAL     EN  99.0  99.0
4  24367          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN   1.0   0.0

## Data cleaning

In [8]:
# Total records 2010 - 2022
len(egresos)

320897

In [9]:
# Check consistency of records expressed in hours
egresos[egresos['CVEEDAD']=='HORAS'].describe()

,ID,DIAS_ESTA,EDAD,PESO,TALLA,LOC
count,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000,3147.000000
mean,156265.399746,8.955513,2.674929,632.688755,643.444550,549.008580
std,92949.096944,13.208121,3.780216,480.484521,460.394712,2245.904554
min,1411.000000,0.000000,1.000000,0.710000,20.000000,1.000000
25%,69918.500000,2.000000,1.000000,3.000000,50.000000,1.000000
50%,157785.000000,4.000000,1.000000,999.000000,999.000000,1.000000
75%,232837.500000,9.500000,2.000000,999.000000,999.000000,3.000000
max,321111.000000,129.000000,23.000000,999.000000,999.000000,9999.000000

In [8]:
# Check consistency of records expressed in days
egresos[egresos['CVEEDAD']=='DIAS'].describe()

,ID,DIAS_ESTA,EDAD,PESO,TALLA,LOC
count,8193.000000,8193.00000,8193.000000,8193.000000,8193.000000,8193.000000
mean,159071.583791,8.85805,7.778103,671.002231,690.502380,245.220066
std,88134.492693,17.39346,7.614351,468.125451,444.851218,1512.634596
min,353.000000,0.00000,1.000000,0.580000,20.000000,1.000000
25%,81755.000000,3.00000,2.000000,3.300000,51.000000,1.000000
50%,157342.000000,5.00000,5.000000,999.000000,999.000000,1.000000
75%,233098.000000,10.00000,11.000000,999.000000,999.000000,1.000000
max,321131.000000,1110.00000,29.000000,999.000000,999.000000,9999.000000

In [10]:
# Check consistency of records expressed in months
egresos[egresos['CVEEDAD']=='MESES'].describe()

,ID,DIAS_ESTA,EDAD,PESO,TALLA,LOC
count,11000.000000,11000.000000,11000.000000,11000.000000,11000.000000,11000.000000
mean,144123.231455,6.663000,4.851273,876.565978,891.758364,116.732909
std,86950.985700,12.387564,3.150333,326.529734,298.614782,988.018192
min,1.000000,0.000000,1.000000,0.840000,21.000000,1.000000
25%,73796.500000,1.000000,2.000000,999.000000,999.000000,1.000000
50%,143374.500000,4.000000,4.000000,999.000000,999.000000,1.000000
75%,214232.000000,7.000000,7.000000,999.000000,999.000000,1.000000
max,321198.000000,448.000000,11.000000,999.000000,999.000000,9999.000000

In [11]:
# Change ages of patients under 1 year to age 0
egresos['EDAD'] = np.where(egresos['CVEEDAD'] != 'AÑOS', 0, egresos['EDAD'])

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,NACIOEN,SEXO,PESO,...,MUNIC,LOC,TIPSERV,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,MESES,0,NO,M,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NaN,NO,MEJORIA
1,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,6,NaN,H,999.0,...,ASIENTOS,3,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
2,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,5,NaN,H,999.0,...,EL LLANO,3,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
3,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,18,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
4,8,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,17,NaN,M,999.0,...,JESUS MARIA,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
5,10,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,4,NaN,M,999.0,...,JESUS MARIA,84,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
6,12,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,12,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
7,14,CENTENARIO HOSPITAL MIGUEL HIDALGO,2009-12-28,2010-01-01,4,AÑOS,4,NaN,H,999.0,...,AGUASCALIENTES,479,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
8,19,CENTENARIO HOSPITAL MIGUEL HIDALGO,2009-12-06,2010-01-05,30,MESES,0,NaN,M,999.0,...,RINCON DE ROMOS,1,NORMAL,CONSULTA EXTERNA,LEUCEMIA MIELOIDE,LEUCEMIA MIELOIDE,SUBSECUENTE,NaN,NO,MEJORIA
9,21,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,5,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
10,22,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-03,2010-01-04,1,AÑOS,72,NaN,M,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,OTRAS ENFERMEDADES DEL ESTÓMAGO Y DEL DUODENO,OTRAS ENFERMEDADES DEL ESTÓMAGO Y DEL DUODENO,SUBSECUENTE,NaN,NO,MEJORIA
11,23,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,25,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
12,24,CENTENARIO HOSPITAL MIGUEL HIDALGO,2009-12-31,2010-01-08,8,AÑOS,79,NaN,H,999.0,...,SAN FRANCISCO DE LOS ROMO,1,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE LA GLÁNDULA TIROIDES,TUMOR MALIGNO DE LA GLÁNDULA TIROIDES,SUBSECUENTE,NaN,NO,MEJORIA
13,26,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,5,NaN,M,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NaN,NO,MEJORIA
14,27,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,45,NaN,M,999.0,...,JESUS MARIA,41,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE LA MAMA,TUMOR MALIGNO DE LA MAMA,SUBSECUENTE,NaN,NO,MEJORIA
15,28,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,21,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
16,29,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-01,2010-01-01,1,AÑOS,15,NaN,M,999.0,...,PABELLON DE ARTEAGA,1,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NaN,NO,MEJORIA
17,30,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-03,2010-01-05,2,AÑOS,10,NaN,H,999.0,...,AGUASCALIENTES,1,NORMAL,CONSULTA EXTERNA,LEUCEMIA MIELOIDE,LEUCEMIA MIELOIDE,SUBSECUENTE,NaN,NO,MEJORIA
18,38,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,50,NaN,M,999.0,...,RINCON DE ROMOS,30,NORMAL,CONSULTA EXTERNA,MASA NO ESPECIFICADA EN LA MAMA,MASA NO ESPECIFICADA EN LA MAMA,PRIMERA,NaN,NO,MEJORIA
19,40,CENTENARIO HOSPITAL MIGUEL HIDALGO,2009-12-31,2010-01-01,1,AÑOS,44,NaN,M,999.0,...,SAN JOSE DE GRACIA,1,NORMAL,CONSULTA EXTERNA,OTROS TRASTORNOS DE LOS MÚSCULOS,OTROS TRASTORNOS DE LOS MÚSCULOS,PRIMERA,NaN,NO,MEJORIA

In [12]:
# Check null values
egresos.isnull().sum()

ID                0
CLUES             0
INGRE             0
EGRESO            0
DIAS_ESTA         0
CVEEDAD           1
EDAD              0
NACIOEN      304937
SEXO              0
PESO              0
TALLA             0
DERHAB            0
MUNIC             0
LOC               0
TIPSERV           3
PROCED            1
DIAG_INI          2
AFECPRIN          3
VEZ               1
CAUSAEXT     290457
INFEC             2
MOTEGRE           1
dtype: int64

In [14]:
# Drop NULL values on columns with 3 or less NULL values
egresos.dropna(subset=['CVEEDAD', 'TIPSERV', 'PROCED', 'DIAG_INI', 'AFECPRIN',
                       'VEZ', 'INFEC', 'MOTEGRE'], inplace=True)

In [15]:
#Drop columns NACIOEN, LOC, they're not neccesary
egresos = egresos.drop(['NACIOEN', 'LOC'], axis = 1)

In [16]:
#Fill NULL values in CAUSAEXT with 'NO APLICA' because they're patients with no lesions
egresos['CAUSAEXT'] = egresos['CAUSAEXT'].fillna('NO APLICA')

In [17]:
#There shouldn't be any more NULL values
egresos.isnull().sum()

ID           0
CLUES        0
INGRE        0
EGRESO       0
DIAS_ESTA    0
CVEEDAD      0
EDAD         0
SEXO         0
PESO         0
TALLA        0
DERHAB       0
MUNIC        0
TIPSERV      0
PROCED       0
DIAG_INI     0
AFECPRIN     0
VEZ          0
CAUSAEXT     0
INFEC        0
MOTEGRE      0
dtype: int64

## Add columns

### Number of medical procedures for each patient

To avoid creating a new column for each procedure (up to a maximum of 77), we calculate the total number of procedures for each unique ID

In [18]:
# Get the maximum value of the procedure number for each ID
conteo = procedimientos.groupby(['ID'])['NUMPROMED'].max().sort_values(ascending = False).to_frame().reset_index()
conteo.NUMPROMED.value_counts()

1     179303
2      69416
3      30987
4      12477
5       5189
6       2342
7       1087
8        877
9        104
11        45
10        43
12        19
13        17
16        14
15         8
21         6
18         6
14         5
17         4
29         4
24         3
25         3
26         3
19         2
20         2
22         2
33         2
46         1
23         1
27         1
31         1
36         1
39         1
77         1
Name: NUMPROMED, dtype: int64

In [19]:
#Merge discharges with the new column
egresos = egresos.merge(conteo, how = 'left', on = 'ID')
#Fill records with no procedures with 0
egresos['NUMPROMED'] = egresos['NUMPROMED'].fillna(0)
egresos.head()

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,SEXO,PESO,TALLA,...,MUNIC,TIPSERV,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE,NUMPROMED
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,MESES,0,M,999.0,999.0,...,AGUASCALIENTES,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0
1,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,6,H,999.0,999.0,...,ASIENTOS,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0
2,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,5,H,999.0,999.0,...,EL LLANO,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0
3,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,18,H,999.0,999.0,...,AGUASCALIENTES,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0
4,8,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,17,M,999.0,999.0,...,JESUS MARIA,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0

### Number of conditions per patient

To avoid creating a new column for each comorbidity (up to a maximum of 10), we calculate the total number of comorbidities for each unique ID

In [20]:
#Obtain the count of the number of conditions per patient
conteo = afecciones.groupby(['ID'])['NUMAFEC'].max().sort_values(ascending = False).to_frame().reset_index()
conteo.NUMAFEC.value_counts()

1     155107
2      32138
3      16219
4       8367
5       3997
6       1935
7        636
8         55
9          8
10         3
Name: NUMAFEC, dtype: int64

In [21]:
#Merge discharges table with the new column
egresos = egresos.merge(conteo, how = 'left', on = 'ID')
egresos.head()

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,SEXO,PESO,TALLA,...,TIPSERV,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE,NUMPROMED,NUMAFEC
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,MESES,0,M,999.0,999.0,...,NORMAL,CONSULTA EXTERNA,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,NaN
1,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,6,H,999.0,999.0,...,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,NaN
2,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,5,H,999.0,999.0,...,NORMAL,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,NaN
3,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,18,H,999.0,999.0,...,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,NaN
4,8,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,17,M,999.0,999.0,...,NORMAL,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,NaN

In [23]:
#Todos los IDS sin afección llenarlos con un cero
egresos['NUMAFEC'] = egresos['NUMAFEC'].fillna(0)
egresos['NUMAFEC'].value_counts()

1.0     155025
0.0     102566
2.0      32105
3.0      16201
4.0       8363
5.0       3997
6.0       1935
7.0        636
8.0         55
9.0          8
10.0         3
Name: NUMAFEC, dtype: int64

### Correction of the number of conditions

With the previous code, we counted the number of comorbidities in the conditions table. The issue is that some comorbidities are the same as the primary condition, which is not possible by definition. In the following code, we will only count the number of patient comorbidities that are not specified as the primary condition.

In [26]:
# Create an empty dictionary
diccionario = {}

# Iterate over each row of the dataframe
for index, row in afecciones.iterrows():
    paciente_id = row['ID']
    comorbilidad = row['AFEC']

    # Check if the patient's ID already exists in the dictionary
    if paciente_id in diccionario:
        # Add the comorbidity to the existing list
        diccionario[paciente_id].append(comorbilidad)
    else:
        # Create a new list of comorbidities for the patient's ID
        diccionario[paciente_id] = [comorbilidad]

In [27]:
# Counter variable
contador = 0

# Iterate through each row of the 'egresos' dataframe
for index, row in egresos.iterrows():
    paciente_id = row['ID']
    afec_principal = row['AFECPRIN']

    # Check if the patient has a primary comorbidity in the dictionary
    if paciente_id in diccionario and afec_principal in diccionario[paciente_id]:
        # Remove the primary comorbidity from the dictionary
        diccionario[paciente_id].remove(afec_principal)
        # Increment the counter
        contador += 1

In [28]:
#Este es el número de registros en los que la afección principal está considerada también como comorbilidad
contador

134018

In [29]:
#Now we obtain the actual number of comorbidities
egresos['NUMAFEC'] = egresos['ID'].apply(lambda x: len(diccionario.get(x, [])))

### Age group to which the patient belongs

Create a new column where patients can be grouped by age range

In [31]:
# Create a list with the conditions
conditions = [
     (egresos['EDAD'] <= 4),
     (egresos['EDAD'] > 4) & (egresos['EDAD'] <= 14),
     (egresos['EDAD'] > 14) & (egresos['EDAD'] <= 29),
     (egresos['EDAD'] > 29) & (egresos['EDAD'] <= 44),
     (egresos['EDAD'] > 44) & (egresos['EDAD'] <= 59),
     (egresos['EDAD'] > 59)]

# Create a list with the values 
values = ['0 a 4', '5 a 14', '15 a 29', '30 a 44', '45 a 59', '60 o más']

# Create a new column to assign the values
egresos['CAT_EDAD'] = np.select(conditions, values)

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,CVEEDAD,EDAD,SEXO,PESO,TALLA,...,PROCED,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE,NUMPROMED,NUMAFEC,CAT_EDAD
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,MESES,0,M,999.0,999.0,...,CONSULTA EXTERNA,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,0 a 4
1,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,AÑOS,6,H,999.0,999.0,...,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,5 a 14
2,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,AÑOS,5,H,999.0,999.0,...,CONSULTA EXTERNA,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,5 a 14
3,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,18,H,999.0,999.0,...,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,15 a 29
4,8,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,AÑOS,17,M,999.0,999.0,...,CONSULTA EXTERNA,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,15 a 29

In [32]:
# Drop CVEEDAD 
egresos.drop(['CVEEDAD'], axis = 1, inplace = True)

### Stay group to which the patient belongs

Create a new column where patients can be grouped by stay range

In [33]:
# Create a list with the conditions
conditions = [
     (egresos['DIAS_ESTA'] <= 1),
     (egresos['DIAS_ESTA'] > 1) & (egresos['DIAS_ESTA'] <= 3),
     (egresos['DIAS_ESTA'] > 3) & (egresos['DIAS_ESTA'] <= 7),
     (egresos['DIAS_ESTA'] > 7) & (egresos['DIAS_ESTA'] <= 30),
    (egresos['DIAS_ESTA'] > 30)]

# Create a list with the values
values = ['1 o menos', '2 a 3', '4 a 7', '8 a 30', 'Más de 30']

# Create a new column to assign the values
egresos['CAT_DIASESTA'] = np.select(conditions, values)

,ID,CLUES,INGRE,EGRESO,DIAS_ESTA,EDAD,SEXO,PESO,TALLA,DERHAB,...,DIAG_INI,AFECPRIN,VEZ,CAUSAEXT,INFEC,MOTEGRE,NUMPROMED,NUMAFEC,CAT_EDAD,CAT_DIASESTA
0,1,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,0,M,999.0,999.0,NE,...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,TUMOR MALIGNO DE OTROS TEJIDOS CONJUNTIVOS Y D...,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,0 a 4,1 o menos
1,3,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-06,2010-01-06,1,6,H,999.0,999.0,NE,...,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,5 a 14,1 o menos
2,4,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-05,2010-01-05,1,5,H,999.0,999.0,NE,...,LEUCEMIA LINFOIDE,LEUCEMIA LINFOIDE,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,5 a 14,1 o menos
3,5,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,18,H,999.0,999.0,NE,...,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,15 a 29,1 o menos
4,8,CENTENARIO HOSPITAL MIGUEL HIDALGO,2010-01-04,2010-01-04,1,17,M,999.0,999.0,NE,...,ENFERMEDAD RENAL CRÓNICA,ENFERMEDAD RENAL CRÓNICA,SUBSECUENTE,NO APLICA,NO,MEJORIA,1.0,0,15 a 29,1 o menos

### Presence of diabetes, hypertension, and obesity

Create three separate columns for Diabetes, Hypertension, and Obesity. Assign 'YES' if the patient has the condition, and 'NO' if not

In [34]:
# Create the 'DIABETES', 'HYPERTENSION', and 'OBESITY' columns in 'egresos' based on the 'afecciones' table
egresos['DIABETES'] = egresos['ID'].isin(afecciones.loc[afecciones['AFEC'] == 'DIABETES MELLITUS TIPO 2', 'ID']).map({True: 'SI', False: 'NO'})
egresos['HIPERTENSION'] = egresos['ID'].isin(afecciones.loc[afecciones['AFEC'] == 'HIPERTENSIÓN ESENCIAL (PRIMARIA)', 'ID']).map({True: 'SI', False: 'NO'})
egresos['OBESIDAD'] = egresos['ID'].isin(afecciones.loc[afecciones['AFEC'] == 'OBESIDAD', 'ID']).map({True: 'SI', False: 'NO'})

In [35]:
# Change the assigned value in the columns in case the primary condition or diagnosis contains these diseases
egresos.loc[(egresos['AFECPRIN'] == 'DIABETES MELLITUS TIPO 2') & (egresos['DIABETES'] == 'NO'), 'DIABETES'] = 'SI'
egresos.loc[(egresos['AFECPRIN'] == 'HIPERTENSIÓN ESENCIAL (PRIMARIA)') & (egresos['HIPERTENSION'] == 'NO'), 'HIPERTENSION'] = 'SI'
egresos.loc[(egresos['AFECPRIN'] == 'OBESIDAD') & (egresos['OBESIDAD'] == 'NO'), 'OBESIDAD'] = 'SI'
egresos.loc[(egresos['DIAG_INI'] == 'DIABETES MELLITUS TIPO 2') & (egresos['DIABETES'] == 'NO'), 'DIABETES'] = 'SI'
egresos.loc[(egresos['DIAG_INI'] == 'HIPERTENSIÓN ESENCIAL (PRIMARIA)') & (egresos['HIPERTENSION'] == 'NO'), 'HIPERTENSION'] = 'SI'
egresos.loc[(egresos['DIAG_INI'] == 'OBESIDAD') & (egresos['OBESIDAD'] == 'NO'), 'OBESIDAD'] = 'SI'

## Initial Exploration

### Discharges

In [36]:
egresos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 320894 entries, 0 to 320893
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            320894 non-null  int64
 1   CLUES         320894 non-null  object
 2   INGRE         320894 non-null  datetime64[ns]
 3   EGRESO        320894 non-null  datetime64[ns]
 4   DIAS_ESTA     320894 non-null  int64
 5   EDAD          320894 non-null  int64
 6   SEXO          320894 non-null  object
 7   PESO          320894 non-null  float64
 8   TALLA         320894 non-null  float64
 9   DERHAB        320894 non-null  object
 10  MUNIC         320894 non-null  object
 11  TIPSERV       320894 non-null  object
 12  PROCED        320894 non-null  object
 13  DIAG_INI      320894 non-null  object
 14  AFECPRIN      320894 non-null  object
 15  VEZ           320894 non-null  object
 16  CAUSAEXT      320894 non-null  object
 17  INFEC         320894 non-null  object
 18  MOTEGRE       320894 non-null  object
 19  NUMPROMED     320894 non-null  float64
 20  NUMAFEC       320894 non-null  int64
 21  CAT_EDAD      320894 non-null  object
 22  CAT_DIASESTA  320894 non-null  object
 23  DIABETES      320894 non-null  object
 24  HIPERTENSION  320894 non-null  object
 25  OBESIDAD      320894 non-null  object
dtypes: datetime64[ns](2), float64(3), int64(4), object(17)
memory usage: 66.1+ MB

In [37]:
# Change data type of NUMPROMED to integer
egresos['NUMPROMED'] = egresos['NUMPROMED'].astype('int64')
egresos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 320894 entries, 0 to 320893
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            320894 non-null  int64
 1   CLUES         320894 non-null  object
 2   INGRE         320894 non-null  datetime64[ns]
 3   EGRESO        320894 non-null  datetime64[ns]
 4   DIAS_ESTA     320894 non-null  int64
 5   EDAD          320894 non-null  int64
 6   SEXO          320894 non-null  object
 7   PESO          320894 non-null  float64
 8   TALLA         320894 non-null  float64
 9   DERHAB        320894 non-null  object
 10  MUNIC         320894 non-null  object
 11  TIPSERV       320894 non-null  object
 12  PROCED        320894 non-null  object
 13  DIAG_INI      320894 non-null  object
 14  AFECPRIN      320894 non-null  object
 15  VEZ           320894 non-null  object
 16  CAUSAEXT      320894 non-null  object
 17  INFEC         320894 non-null  object
 18  MOTEGRE       320894 non-null  object
 19  NUMPROMED     320894 non-null  int64
 20  NUMAFEC       320894 non-null  int64
 21  CAT_EDAD      320894 non-null  object
 22  CAT_DIASESTA  320894 non-null  object
 23  DIABETES      320894 non-null  object
 24  HIPERTENSION  320894 non-null  object
 25  OBESIDAD      320894 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(5), object(17)
memory usage: 66.1+ MB

In [38]:
egresos.describe()

,ID,DIAS_ESTA,EDAD,PESO,TALLA,NUMPROMED,NUMAFEC
count,320894.000000,320894.000000,320894.000000,320894.000000,320894.000000,320894.00000,320894.000000
mean,160803.790005,3.102897,30.945957,852.253243,871.367090,1.61717,0.627151
std,92653.293244,8.125905,23.264736,340.954951,304.843539,1.22473,1.005071
min,1.000000,0.000000,0.000000,0.580000,15.000000,0.00000,0.000000
25%,80592.250000,1.000000,14.000000,999.000000,999.000000,1.00000,0.000000
50%,160815.500000,1.000000,26.000000,999.000000,999.000000,1.00000,0.000000
75%,241038.750000,3.000000,46.000000,999.000000,999.000000,2.00000,1.000000
max,321262.000000,1838.000000,130.000000,999.000000,999.000000,77.00000,10.000000

The shortest stay is 0 days, the longest is 1838 days. The average stay is 3 days, and the most common stay duration is 1 day.

The youngest age is 0 years, the oldest is 130 years. The average age is 31 years. 50% of the patients are 26 years old or younger.

More than 75% of our age and weight data are unspecified (999).

The smallest number of procedures is 0, and the largest is 77. The average number of procedures is 2. 50% of patients have 1 procedure or fewer.

The smallest number of comorbidities is 0, and the largest is 10. The average number of comorbidities is 1. 75% of patients have one comorbidity or fewer.

### Affections

In [39]:
afecciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335485 entries, 0 to 335484
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   ID       335485 non-null  int64
 1   NUMAFEC  335485 non-null  int64
 2   AFEC     335485 non-null  object
dtypes: int64(2), object(1)
memory usage: 7.7+ MB

In [40]:
afecciones.describe()

                  ID        NUMAFEC
count  335485.000000  335485.000000
mean   186890.008260       1.636854
std     86740.347783       1.071359
min         6.000000       1.000000
25%    125992.000000       1.000000
50%    197172.000000       1.000000
75%    259366.000000       2.000000
max    321262.000000      10.000000

### Procedures

In [41]:
procedimientos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 519460 entries, 0 to 519459
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   ID         519460 non-null  int64
 1   NUMPROMED  519460 non-null  int64
 2   TIPO       519460 non-null  object
 3   PROMED     519460 non-null  object
 4   ANEST      519460 non-null  object
 5   QUIROF     519460 non-null  object
 6   QH         238223 non-null  float64
 7   QM         238182 non-null  float64
dtypes: float64(2), int64(2), object(4)
memory usage: 31.7+ MB

In [42]:
procedimientos.isnull().sum()

ID                0
NUMPROMED         0
TIPO              0
PROMED            0
ANEST             0
QUIROF            0
QH           281237
QM           281278
dtype: int64

In [43]:
#Check if there are null records for operating room time when the operating room has actually been used.
df = procedimientos[procedimientos['QUIROF']=='EN']
df.isnull().sum()

ID            0
NUMPROMED     0
TIPO          0
PROMED        0
ANEST         0
QUIROF        0
QH            1
QM           42
dtype: int64

In [44]:
#Assign a value of 0 to null records where the operating room was not used.
procedimientos.loc[(procedimientos['QUIROF'] != 'EN') &
                   ((procedimientos['QH'].isnull()) | (procedimientos['QM'].isnull())), ['QH', 'QM']] = 0
# verify that the only remaining null values correspond to patients who entered the operating room.
procedimientos.isnull().sum()

ID            0
NUMPROMED     0
TIPO          0
PROMED        0
ANEST         0
QUIROF        0
QH            1
QM           42
dtype: int64

In [45]:
# the only null record for hours
df[df['QH'].isnull()]

,ID,NUMPROMED,TIPO,PROMED,ANEST,QUIROF,QH,QM
423205,275551,4,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,NaN,NaN

In [46]:
#In general, for this procedure, we don't have operating room time values (99 represents 'NE' or 'Not Evaluated,' and 0 is not a real value)
#there's a record of only 1 minute, which was likely a mistake, and it should have been 1 hour
df[df['PROMED']=='PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCICA, PLEURA, MEDIASTINO Y DIAFRAGMA']

,ID,NUMPROMED,TIPO,PROMED,ANEST,QUIROF,QH,QM
3088,2879,5,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,99.0,99.0
36048,2724,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,99.0,99.0
36055,2803,6,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,99.0,99.0
56566,36661,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,99.0,99.0
61846,32139,2,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,99.0,99.0
...,...,...,...,...,...,...,...,...
465497,287581,2,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,0.0
465498,287581,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,0.0
465587,287439,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,0.0
465653,298023,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,0.0
473421,300295,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,1.0

In [47]:
# Check values that are neither 0 nor 99 for this procedure
df[(df['PROMED']=='PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCICA, PLEURA, MEDIASTINO Y DIAFRAGMA')
  & (((df['QH']>0) & (df['QH']<99)) | ((df['QM']>0) & (df['QM']<99)))]

,ID,NUMPROMED,TIPO,PROMED,ANEST,QUIROF,QH,QM
141434,98683,5,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,0.0,30.0
142498,99226,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,LOCAL,EN,0.0,30.0
182256,114856,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,1.0,0.0
216453,148268,4,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,0.0,30.0
284844,196031,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,1.0,0.0
317014,220453,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,2.0,30.0
320502,215717,2,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,COMBINADA,EN,1.0,0.0
327710,223666,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,1.0,0.0
328583,226027,2,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,REGIONAL,EN,1.0,0.0
331276,223086,2,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,1.0,0.0
371390,251608,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,COMBINADA,EN,0.0,50.0
386728,250844,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,2.0,0.0
405989,266400,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,1.0,0.0
410152,269277,4,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,20.0
420243,274901,5,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,30.0
420246,274901,4,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,30.0
452426,297894,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,COMBINADA,EN,1.0,0.0
454836,288640,3,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,2.0,0.0
455647,298000,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,2.0,0.0
473421,300295,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE PARED TORÁCI...,GENERAL,EN,0.0,1.0

In [48]:
#There are also many surgeries where no time is recorded
df[(df['QH']==0)&(df['QM']==0)]

,ID,NUMPROMED,TIPO,PROMED,ANEST,QUIROF,QH,QM
313601,218285,1,QUIRURGICO,SUSTITUCIÓN DE LAS ARTICULACIONES DE LAS EXTRE...,REGIONAL,EN,0.0,0.0
313602,220519,1,QUIRURGICO,REDUCCIÓN ABIERTA DE FRACTURA CON FIJACIÓN INT...,GENERAL,EN,0.0,0.0
313603,214528,1,QUIRURGICO,TIROIDECTOMÍA TOTAL,GENERAL,EN,0.0,0.0
313604,217543,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE RIÑÓN,LOCAL,EN,0.0,0.0
313605,219754,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE ESÓFAGO,GENERAL,EN,0.0,0.0
...,...,...,...,...,...,...,...,...
469502,291325,1,QUIRURGICO,HIPOFISECTOMÍA,GENERAL,EN,0.0,0.0
469504,291323,1,DIAGNOSTICO,PROCEDIMIENTOS DIAGNÓSTICOS SOBRE MAMA,SEDACION,EN,0.0,0.0
469505,291323,2,QUIRURGICO,EXTIRPACIÓN O DESTRUCCIÓN DE TEJIDO DE LA MAMA,SEDACION,EN,0.0,0.0
469506,291323,3,QUIRURGICO,SUTURA U OTRO CIERRE DE PIEL Y TEJIDO SUBCUTÁNEO,SEDACION,EN,0.0,0.0
469507,291322,1,QUIRURGICO,REPARACIÓN DE OTRA HERNIA DE LA PARED ABDOMINA...,SEDACION,EN,0.0,0.0

In [49]:
#There are also procedures that last very few minutes, some of which are possible, but others are not
df[(df['QH']==0)&(df['QM']<10)&(df['QM']>0)]

,ID,NUMPROMED,TIPO,PROMED,ANEST,QUIROF,QH,QM
313944,221333,1,QUIRURGICO,LOBECTOMÍA TIROIDEA UNILATERAL,GENERAL,EN,0.0,5.0
316778,217460,1,QUIRURGICO,APENDICECTOMÍA,REGIONAL,EN,0.0,1.0
318697,220345,1,QUIRURGICO,EXTRACCIÓN EXTRACAPSULAR DE CRISTALINO MEDIANT...,SEDACION,EN,0.0,4.0
320201,217679,1,QUIRURGICO,EXTRACCIÓN QUIRÚRGICA DE DIENTE,GENERAL,EN,0.0,5.0
320202,217679,2,QUIRURGICO,EXTRACCIÓN QUIRÚRGICA DE DIENTE,GENERAL,EN,0.0,2.0
...,...,...,...,...,...,...,...,...
519180,321202,3,TERAPEUTICO,INYECCIÓN O INFUSIÓN DE OTRA SUSTANCIA TERAPÉU...,NO USO,EN,0.0,1.0
519310,321230,2,QUIRURGICO,"EXPLORACIÓN MANUAL DE LA CAVIDAD UTERINA, DESP...",NO USO,EN,0.0,5.0
519328,321235,1,QUIRURGICO,"EXPLORACIÓN MANUAL DE LA CAVIDAD UTERINA, DESP...",NO USO,EN,0.0,1.0
519403,321251,5,TERAPEUTICO,PROCEDIMIENTOS QUE REDUCEN LA MORBILIDAD Y LA ...,LOCAL,EN,0.0,1.0
519428,321256,2,QUIRURGICO,"EXPLORACIÓN MANUAL DE LA CAVIDAD UTERINA, DESP...",LOCAL,EN,0.0,1.0

In [50]:
#There are many incorrect values, and it's not possible to check each procedure for logical or illogical values.
#We remove the columns to avoid potential issues.
procedimientos = procedimientos.drop(['QH', 'QM'], axis = 1)
procedimientos.head()

      ID  NUMPROMED        TIPO       PROMED     ANEST QUIROF
0  10952          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN
1  23436          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN
2  23659          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN
3  23789          1  QUIRURGICO  LAPAROTOMÍA   GENERAL     EN
4  24367          1  QUIRURGICO  LAPAROTOMÍA  REGIONAL     EN

## Export to csv

In [51]:
from pathlib import Path
#Egresos
filepath = Path('../../Data/Databases/To viz/egresos.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
egresos.to_csv(filepath, index = False)

In [52]:
#Procedimientos
filepath = Path('../../Data/Databases/To viz/procedimientos.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
procedimientos.to_csv(filepath, index = False)

In [53]:
#Afecciones
filepath = Path('../../Data/Databases/To viz/afecciones.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
afecciones.to_csv(filepath, index = False)